services:
  postgres:
    image: postgres:16
    container_name: schedulr_postgres
    environment:
      POSTGRES_USER: schedulr
      POSTGRES_PASSWORD: schedulr
      POSTGRES_DB: schedulr
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
